'use strict';

// ===== TRANSLATIONS =====
const TRANS = {
  vi: {
    // NAV
    'nav.home':'Trang chủ','nav.find_guide':'Tìm HDV','nav.post_request':'Đăng yêu cầu',
    'nav.become_guide':'Làm HDV','nav.login':'Đăng nhập','nav.logout':'Đăng xuất',
    'nav.dashboard':'Dashboard','nav.tourist_dash':'Dashboard của tôi',
    // GUIDE CARD
    'card.verified':'Đã xác minh','card.reviews':'đánh giá','card.from':'Từ',
    'card.per_day':'/ ngày','card.view_profile':'Xem hồ sơ',
    'card.experience':'năm kinh nghiệm','card.response_time':'Phản hồi',
    // INDEX
    'home.trust_badge':'Nền tảng đáng tin cậy #1 Việt Nam',
    'home.hero_title':'Lịch trình du lịch<br><span>cá nhân hóa</span> cho bạn',
    'home.hero_sub':'Muốn đi Nha Trang nhưng chưa biết lên kế hoạch? Tìm HDV địa phương — họ sẽ thiết kế hành trình phù hợp 100% với sở thích của bạn.',
    'home.search_ph':'Bạn muốn đi đâu? Nha Trang, Đà Lạt, Sapa...',
    'home.search_btn':'Tìm HDV',
    'home.how_tag':'Cách hoạt động','home.how_title':'Đơn giản chỉ 3 bước',
    'home.how_sub':'Không cần mày mò tìm kiếm, không lo bị "chặt chém" — HDV địa phương lo mọi thứ cho bạn',
    'home.step1_t':'Tìm HDV','home.step1_d':'Tìm hướng dẫn viên theo điểm đến, ngân sách và đánh giá từ khách đã đi.',
    'home.step2_t':'Gửi yêu cầu','home.step2_d':'Chia sẻ sở thích, ngân sách, ngày đi — HDV sẽ lên lịch trình riêng cho bạn trong 24h.',
    'home.step3_t':'Tận hưởng','home.step3_d':'Xác nhận lịch trình, đặt cọc an toàn qua nền tảng và chuẩn bị cho chuyến đi tuyệt vời.',
    'home.feat_tag':'HDV nổi bật','home.feat_title':'Hướng Dẫn Viên Được Yêu Thích',
    'home.feat_sub':'Những HDV địa phương được đánh giá cao nhất bởi hàng trăm khách du lịch',
    'home.see_all':'Xem tất cả',
    'home.dest_tag':'Điểm đến','home.dest_title':'Khám Phá Việt Nam',
    'home.dest_sub':'HDV địa phương am hiểu tại mỗi điểm đến — từ bãi biển phía Nam đến núi rừng Tây Bắc',
    'home.stat_happy':'Khách hài lòng','home.stat_guides':'HDV được xác minh',
    'home.stat_dest':'Điểm đến','home.stat_rate':'Hài lòng',
    'home.why_tag':'Tại sao chọn chúng tôi','home.why_title':'Trải Nghiệm Khác Biệt',
    'home.w1_t':'100% cá nhân hóa','home.w1_d':'Lịch trình thiết kế riêng theo sở thích, ngân sách và thời gian của bạn.',
    'home.w2_t':'HDV địa phương thật','home.w2_d':'Người dân địa phương, biết những điểm ăn ngon, góc đẹp mà tour thường không đến.',
    'home.w3_t':'Thanh toán an toàn','home.w3_d':'Tiền được giữ bởi nền tảng, chỉ chuyển cho HDV sau khi bạn hoàn thành chuyến đi.',
    'home.w4_t':'HDV đã xác minh','home.w4_d':'Tất cả HDV được kiểm tra chứng chỉ, đánh giá thật từ khách đã đi.',
    'home.cta_title':'Chuyến đi trong mơ bắt đầu từ đây',
    'home.cta_sub':'Gửi yêu cầu miễn phí — HDV phản hồi trong 24 giờ',
    'home.cta_btn':'Gửi Yêu Cầu Miễn Phí','home.cta_browse':'Xem Tất Cả HDV',
    // GUIDES PAGE
    'guides.title':'Tìm Hướng Dẫn Viên',
    'guides.sub':'Hơn 50 HDV địa phương được xác minh — tìm người phù hợp với chuyến đi của bạn',
    'guides.filter':'Bộ lọc','guides.dest_label':'Điểm đến','guides.all_dest':'Tất cả điểm đến',
    'guides.price_label':'Giá / ngày (tối đa)','guides.rating_label':'Đánh giá tối thiểu',
    'guides.all_ratings':'Tất cả','guides.clear':'Xóa bộ lọc',
    'guides.tip_title':'💡 Mẹo hay',
    'guides.tip_text':'Chưa biết chọn HDV nào? Hãy <a href="request.html" style="color:var(--blue);font-weight:600">đăng yêu cầu</a> — chúng tôi sẽ ghép HDV phù hợp nhất cho bạn!',
    'guides.popular':'Phổ biến nhất','guides.top_rated':'Đánh giá cao nhất',
    'guides.price_asc':'Giá thấp nhất','guides.price_desc':'Giá cao nhất',
    'guides.count_suffix':'hướng dẫn viên',
    'guides.no_result':'Không tìm thấy HDV','guides.no_result_sub':'Thử thay đổi bộ lọc',
    // PROFILE PAGE
    'profile.about':'Giới Thiệu','profile.itineraries':'Lịch Trình Mẫu',
    'profile.itin_note':'Đây là lịch trình mẫu. HDV sẽ tùy chỉnh theo yêu cầu của bạn.',
    'profile.reviews':'Đánh Giá Từ Khách','profile.trips':'Chuyến đã dẫn',
    'profile.reviews_stat':'Đánh giá','profile.per_day':'/ ngày',
    'profile.price_from':'Giá dịch vụ từ',
    'profile.price_note':'Giá cuối tùy theo lịch trình & yêu cầu của bạn',
    'profile.start_date':'Ngày bắt đầu','profile.num_days':'Số ngày','profile.num_people':'Số người',
    'profile.estimated':'Dự kiến','profile.send_request':'Gửi Yêu Cầu',
    'profile.free':'Miễn phí gửi yêu cầu','profile.resp_24h':'HDV phản hồi trong 24h',
    'profile.pay_after':'Thanh toán sau khi chốt lịch trình','profile.share':'Chia sẻ hồ sơ này',
    // REQUEST PAGE
    'req.title':'Đăng Yêu Cầu Chuyến Đi',
    'req.sub':'Mô tả chuyến đi bạn mong muốn — HDV phù hợp sẽ liên hệ trong 24 giờ',
    'req.name':'Họ và tên','req.phone':'Số điện thoại','req.email':'Email',
    'req.dest':'Điểm đến mong muốn','req.date':'Ngày bắt đầu dự kiến',
    'req.days':'Số ngày','req.people':'Số người','req.budget':'Ngân sách',
    'req.interests':'Sở thích & Hoạt động','req.notes':'Ghi chú thêm',
    'req.notes_ph':'Thông tin thêm về chuyến đi của bạn...','req.submit':'Gửi Yêu Cầu',
    'req.free_note':'Miễn phí · Không cam kết · HDV liên hệ trong 24h',
    // PAYMENT PAGE
    'pay.contact':'Thông tin liên hệ','pay.name':'Họ và tên','pay.phone':'Số điện thoại',
    'pay.email':'Email','pay.notes':'Ghi chú thêm','pay.notes_ph':'Yêu cầu đặc biệt, sở thích...',
    'pay.method':'Phương thức thanh toán','pay.domestic':'🇻🇳 Trong nước','pay.intl':'🌍 Quốc tế',
    'pay.escrow':'<i class="fa-solid fa-shield-halved" style="margin-right:6px"></i><strong>Thanh toán ký quỹ an toàn:</strong> Tiền của bạn được giữ bởi GuideTravel và chỉ chuyển cho HDV sau khi tour hoàn thành.',
    'pay.confirm_btn':'<i class="fa-solid fa-lock"></i> Xác nhận & Thanh toán an toàn',
    'pay.ssl_note':'<i class="fa-solid fa-shield-halved"></i> Thanh toán được mã hóa SSL. Bạn có thể hủy miễn phí trước 7 ngày.',
    'pay.summary':'Tóm tắt đặt tour','pay.start_date':'Ngày bắt đầu','pay.days':'Số ngày',
    'pay.people':'Số người','pay.unit_price':'Đơn giá','pay.service_fee':'Phí dịch vụ',
    'pay.free':'Miễn phí','pay.total':'Tổng cộng',
    'pay.trust1':'Hoàn tiền 100% nếu hủy trước 7 ngày','pay.trust2':'HDV xác nhận trong 24h',
    'pay.trust3':'Thanh toán được bảo vệ','pay.trust4':'Hỗ trợ 24/7 trong suốt chuyến đi',
    'pay.view_policy':'Xem chính sách hoàn tiền',
    'pay.success_title':'Đặt tour thành công!',
    'pay.success_sub':'Yêu cầu của bạn đã được gửi đến HDV. Họ sẽ liên hệ lại trong vòng 24 giờ để xác nhận lịch trình.',
    'pay.save_code':'Lưu mã này để theo dõi yêu cầu của bạn',
    'pay.back_home':'Về trang chủ','pay.find_more':'Tìm HDV khác',
    'pay.step1':'Chọn HDV','pay.step2':'Điền thông tin','pay.step3':'Thanh toán','pay.step4':'Xác nhận',
    // LOGIN
    'login.platform_sub':'Nền tảng kết nối du khách & hướng dẫn viên',
    'login.tab_login':'Đăng nhập','login.tab_register':'Đăng ký',
    'login.tourist':'Du khách','login.guide':'Hướng dẫn viên',
    'login.email_ph':'email@example.com','login.pass_ph':'••••••••',
    'login.login_btn':'<i class="fa-solid fa-right-to-bracket"></i> Đăng nhập',
    'login.no_account':'Chưa có tài khoản?','login.register_now':'Đăng ký ngay',
    'login.name_ph':'Nguyễn Văn A','login.phone_ph':'0912 345 678',
    'login.pass_ph2':'Tối thiểu 6 ký tự',
    'login.create_btn':'<i class="fa-solid fa-user-plus"></i> Tạo tài khoản',
    'login.have_account':'Đã có tài khoản?','login.login_link':'Đăng nhập',
    // FOOTER
    'footer.brand_sub':'Kết nối du khách với hướng dẫn viên địa phương để tạo ra những hành trình cá nhân hóa đáng nhớ.',
    'footer.explore':'Khám Phá','footer.services':'Dịch Vụ','footer.contact':'Liên Hệ',
    'footer.find_guides':'Tìm HDV','footer.post_request':'Đăng yêu cầu tour',
    'footer.all_dest':'Tất cả điểm đến','footer.become_guide':'Đăng ký làm HDV',
    'footer.refund':'Chính sách hoàn tiền','footer.faq':'FAQ',
    'footer.copyright':'© 2024 GuideTravel. Bảo lưu mọi quyền.',
    'footer.brand_tagline':'Nền tảng kết nối du lịch cá nhân hóa',
    // DESTINATIONS
    'dest.beach':'Biển đảo','dest.culture':'Văn hóa','dest.trekking':'Trekking',
    'dest.nature':'Thiên nhiên','dest.island':'Đảo ngọc',
    // GUIDES PAGE EXTRA
    'guides.breadcrumb':'Tìm HDV',
    'guides.search_lbl':'Tìm theo tên','guides.search_ph':'Tên hướng dẫn viên...',
    'guides.lang_lbl':'Ngôn ngữ HDV','guides.lang_all':'Tất cả ngôn ngữ',
    'guides.filter_h':'Bộ lọc','guides.dest_filter':'Điểm đến',
    'guides.dest_all':'Tất cả điểm đến','guides.price_max':'Giá / ngày (tối đa)',
    'guides.rating_min':'Đánh giá tối thiểu','guides.reset':'Xóa bộ lọc',
    'guides.tip_h':'💡 Mẹo hay',
    'guides.dest_title':'Điểm Đến','guides.services_title':'Dịch Vụ',
    // REQUEST PAGE EXTRA
    'req.page_title':'Mô Tả Chuyến Đi Của Bạn',
    'req.page_sub':'Chỉ mất 2 phút — HDV sẽ phản hồi lịch trình trong 24 giờ',
    'req.form_title':'Thông Tin Chuyến Đi',
    'req.form_sub':'Càng chi tiết, HDV càng dễ thiết kế lịch trình phù hợp cho bạn',
    'req.your_info':'Thông tin của bạn','req.trip_info':'Thông tin chuyến đi',
    'req.likes':'Bạn thích gì?','req.pick_multi':'(chọn nhiều)',
    'req.extra_notes':'Yêu cầu thêm / Ghi chú',
    'req.notes_hint':'Thông tin này giúp HDV thiết kế lịch trình phù hợp hơn',
    'req.submit_btn':'Gửi Yêu Cầu Miễn Phí',
    'req.privacy':'Thông tin của bạn được bảo mật tuyệt đối',
    'req.next_title':'Tiếp theo sẽ như thế nào?',
    'req.s1t':'HDV nhận yêu cầu','req.s1d':'Trong vài giờ, HDV phù hợp sẽ xem yêu cầu của bạn',
    'req.s2t':'Nhận lịch trình trong 24h','req.s2d':'HDV gửi lịch trình chi tiết + báo giá qua email/điện thoại',
    'req.s3t':'Chỉnh sửa miễn phí','req.s3d':'Thoải mái điều chỉnh lịch trình cho đến khi ưng ý',
    'req.s4t':'Xác nhận & Đặt cọc','req.s4d':'Đặt cọc 30% an toàn qua nền tảng để chốt lịch',
    'req.suggest_h':'HDV có thể phù hợp','req.suggest_all':'Xem tất cả HDV →',
    'req.pledge_h':'Cam kết của GuideTravel',
    'req.pledge1':'Gửi yêu cầu hoàn toàn miễn phí',
    'req.pledge2':'Không bị ép đặt tour nếu chưa ưng',
    'req.pledge3':'Hoàn tiền 100% nếu hủy trước 7 ngày',
    'req.success_h':'Yêu Cầu Đã Được Gửi! 🎉',
    'req.success_p':'Cảm ơn bạn đã gửi yêu cầu. HDV sẽ liên hệ với bạn qua điện thoại và email trong vòng <strong>24 giờ</strong> để gửi lịch trình cá nhân hóa.',
    'req.code_lbl':'Mã yêu cầu của bạn',
    'req.waiting_h':'Trong lúc chờ đợi...',
    'req.wait1':'Kiểm tra email để nhận thông báo',
    'req.wait2':'Để ý điện thoại — HDV có thể gọi trực tiếp',
    'req.wait3':'Xem thêm hồ sơ các HDV khác',
    'req.see_more':'Xem Thêm HDV','req.back_home':'Trang Chủ',
    // PROFILE PAGE EXTRA
    'profile.resp_lbl':'Phản hồi',
    'profile.about_h':'Giới Thiệu','profile.itin_h':'Lịch Trình Mẫu',
    'profile.reviews_h':'Đánh Giá Từ Khách',
    'profile.price_from_lbl':'Giá dịch vụ từ','profile.per_day_lbl':'/ ngày',
    'profile.price_note_lbl':'Giá cuối tùy theo lịch trình & yêu cầu của bạn',
    'profile.start_lbl':'Ngày bắt đầu','profile.days_lbl':'Số ngày','profile.people_lbl':'Số người',
    'profile.est_lbl':'Dự kiến','profile.req_btn':'Gửi Yêu Cầu',
    'profile.g1':'Miễn phí gửi yêu cầu','profile.g2':'HDV phản hồi trong 24h',
    'profile.g3':'Thanh toán sau khi chốt lịch trình',
    'profile.share_h':'Chia sẻ hồ sơ này',
    // LOGIN EXTRA
    'login.pass_lbl':'Mật khẩu','login.name_lbl':'Họ và tên',
    'login.phone_lbl':'Số điện thoại',
    'login.login_btn_text':'Đăng nhập','login.create_text':'Tạo tài khoản',
    // UNITS
    'unit.days':'ngày','unit.hours':'giờ','unit.people':'người',
    // SPECIALTIES
    'spec.Biển đảo':'Biển đảo','spec.Lặn biển':'Lặn biển','spec.Ẩm thực':'Ẩm thực',
    'spec.Văn hóa':'Văn hóa','spec.Lịch sử':'Lịch sử','spec.Chụp ảnh':'Chụp ảnh',
    'spec.Trekking':'Trekking','spec.Văn hóa dân tộc':'Văn hóa dân tộc',
    'spec.Nhiếp ảnh':'Nhiếp ảnh','spec.Cắm trại':'Cắm trại',
    'spec.Thiên nhiên':'Thiên nhiên','spec.Cà phê':'Cà phê',
    // INTERESTS
    'int.beach':'Biển & Bơi lội','int.trekking':'Trekking','int.food':'Ẩm thực',
    'int.culture':'Văn hóa','int.photo':'Chụp ảnh','int.shopping':'Mua sắm',
    'int.relax':'Nghỉ dưỡng','int.village':'Bản làng','int.watersport':'Thể thao biển',
    // PAYMENT EXTRA
    'pay.page_title':'Xác nhận & Thanh toán',
    'pay.bank_transfer':'Chuyển khoản',
    'pay.wise_fee':'Phí thấp nhất',
    // NAV
    'nav.about':'Giới thiệu','nav.blog':'Blog',
    // BLOG
    'blog.title':'Blog Du Lịch Việt Nam',
    'blog.sub':'Kinh nghiệm thực tế từ hướng dẫn viên địa phương — mẹo hay, điểm đến, ngân sách',
    'blog.search_ph':'Tìm bài viết...',
    'blog.cat_all':'Tất cả','blog.cat_dest':'Điểm đến','blog.cat_tip':'Mẹo hay','blog.cat_guide':'Hướng dẫn',
    'blog.popular':'Bài viết phổ biến','blog.tags':'Chủ đề',
    'blog.cta_h':'Sẵn sàng khám phá?','blog.cta_p':'Gửi yêu cầu miễn phí — HDV địa phương sẽ lên lịch trình riêng cho bạn.',
    'blog.cta_btn':'Đăng yêu cầu ngay',
    // POST
    'post.share':'Chia sẻ:','post.copy_link':'Copy link',
    'post.related':'Bài viết liên quan','post.toc':'Mục lục',
    'post.guides_region':'HDV khu vực này','post.see_all_guides':'Xem tất cả HDV',
    // ABOUT PAGE
    'about.tag':'Câu chuyện của chúng tôi',
    'about.hero_title':'Du lịch Việt Nam nên được<br><span style="color:var(--blue)">trải nghiệm như người địa phương</span>',
    'about.hero_sub':'GuideTravel sinh ra từ một câu hỏi đơn giản: Tại sao du khách nước ngoài phải chịu đựng những tour đại trà đắt tiền, trong khi những người dân địa phương am hiểu đang ở ngay bên cạnh?',
    'about.mission_tag':'Sứ mệnh','about.mission_title':'Kết nối con người, không chỉ điểm đến',
    'about.mission_p1':'Chúng tôi tin rằng du lịch thật sự bắt đầu khi bạn gặp được người địa phương — người biết con hẻm nào có bún bò ngon nhất, bãi biển nào chưa có khách du lịch.',
    'about.mission_p2':'GuideTravel là nền tảng kết nối trực tiếp giữa du khách và hướng dẫn viên địa phương được xác minh — không qua trung gian, không lịch trình đại trà, 100% cá nhân hóa.',
    'about.values_tag':'Giá trị cốt lõi','about.values_title':'Những gì chúng tôi tin tưởng',
    'about.v1_t':'Tin tưởng & Minh bạch','about.v1_d':'Mọi HDV đều được xác minh danh tính và chứng chỉ. Đánh giá 100% từ khách thật, không chỉnh sửa.',
    'about.v2_t':'Cá nhân hóa tuyệt đối','about.v2_d':'Không có lịch trình copy-paste. Mỗi chuyến đi được thiết kế riêng dựa trên sở thích, ngân sách và thời gian của bạn.',
    'about.v3_t':'Hỗ trợ cộng đồng địa phương','about.v3_d':'80% doanh thu đến tay HDV và cộng đồng địa phương. Du lịch có trách nhiệm với môi trường và văn hóa.',
    'about.v4_t':'An toàn & Bảo mật','about.v4_d':'Thanh toán ký quỹ bảo vệ cả hai bên. Tiền chỉ giải ngân sau khi tour hoàn thành và khách xác nhận.',
    'about.how_tag':'Cách chúng tôi hoạt động','about.how_title':'Mô hình marketplace<br>minh bạch',
    'about.how_p':'GuideTravel hoạt động như một sàn giao dịch: chúng tôi kết nối và xác thực, còn HDV tự quyết định giá dịch vụ.',
    'about.how_s1t':'HDV đăng ký & được xác minh','about.how_s1d':'Kiểm tra CMND, chứng chỉ hướng dẫn viên, phỏng vấn trực tiếp',
    'about.how_s2t':'Khách gửi yêu cầu miễn phí','about.how_s2d':'Mô tả chuyến đi, HDV phù hợp nhất phản hồi trong 24h',
    'about.how_s3t':'Thanh toán ký quỹ an toàn','about.how_s3d':'Tiền giữ bởi nền tảng, giải ngân sau khi tour hoàn thành',
    'about.how_s4t':'Đánh giá thật, minh bạch','about.how_s4d':'Chỉ khách đã hoàn thành tour mới được đánh giá HDV',
    'about.revenue_title':'Phân chia doanh thu','about.rev_guide':'HDV nhận được',
    'about.rev_platform':'Nền tảng (vận hành, hỗ trợ)','about.rev_note':'HDV có thể chọn mức hoa hồng 15–30% để xuất hiện cao hơn trong kết quả tìm kiếm.',
    'about.story_tag':'Lịch sử hình thành','about.story_title':'Từ ý tưởng đến nền tảng',
    'about.tl1_t':'Ý tưởng nảy sinh','about.tl1_d':'Founder trải nghiệm tour đại trà tại Hội An và nhận ra sự khác biệt khi được người dân địa phương dẫn đi.',
    'about.tl2_t':'Thử nghiệm đầu tiên','about.tl2_d':'Ra mắt beta với 5 HDV tại Nha Trang và Hội An. 50 booking đầu tiên trong 3 tháng.',
    'about.tl3_t':'Mở rộng toàn quốc','about.tl3_d':'Mở rộng ra 8 tỉnh thành, onboard 50+ HDV, đạt 500 booking tích lũy.',
    'about.tl4_t':'Hướng đến khách quốc tế','about.tl4_d':'Ra mắt giao diện tiếng Anh, tích hợp thanh toán quốc tế Stripe, mục tiêu 1,000 booking/tháng.',
    'about.team_tag':'Đội ngũ','about.team_title':'Những người đứng sau GuideTravel',
    'about.role_ceo':'Co-founder & CEO','about.bio_ceo':'10 năm ngành du lịch, cựu product manager tại Traveloka Vietnam.',
    'about.role_cto':'Co-founder & CTO','about.bio_cto':'Full-stack engineer 8 năm, từng xây dựng hệ thống booking cho 50K+ người dùng.',
    'about.role_ops':'Head of Guide Operations','about.bio_ops':'Cựu HDV quốc tế 6 năm, phụ trách xét duyệt và đào tạo HDV.',
    'about.cta_title':'Muốn trải nghiệm khác biệt?','about.cta_sub':'Gửi yêu cầu miễn phí — HDV địa phương phản hồi trong 24 giờ',
    // 404 PAGE
    'err.title':'Trang này chưa được khám phá',
    'err.sub':'Có vẻ như bạn đã đi lạc vào một điểm đến chưa có trên bản đồ. Để chúng tôi đưa bạn trở về đúng đường.',
    'err.go_home':'Về trang chủ','err.browse_guides':'Tìm HDV',
    'err.popular':'Hoặc xem các trang phổ biến:',
    // TOAST / VALIDATION
    'err.select_date':'Vui lòng chọn ngày bắt đầu!',
    'err.fill_form':'Vui lòng điền đầy đủ thông tin!',
    // COMMISSION TIERS
    'tier.top':'🏆 Nổi bật #1','tier.featured':'⭐ Đề xuất','tier.priority':'👍 Ưu tiên',
    // REQUEST
    'req.all_guides':'Tất cả HDV phù hợp',
    'review.you':'Bạn',
    // CHINH SACH PAGE
    'cs.breadcrumb':'Chính sách',
    'cs.page_h1':'Chính Sách Hoàn Tiền & Bảo Vệ',
    'cs.page_sub':'Minh bạch — công bằng — bảo vệ quyền lợi tất cả các bên',
    'cs.nav_contents':'Nội dung',
    'cs.nav_refund':'Chính sách hoàn tiền',
    'cs.nav_cancel':'Hủy tour',
    'cs.nav_force':'Bất khả kháng',
    'cs.nav_dispute':'Giải quyết tranh chấp',
    'cs.nav_protect':'Bảo vệ nền tảng',
    'cs.nav_payment':'Quy trình thanh toán',
    'cs.nav_support':'Liên hệ hỗ trợ',
    'cs.commit_title':'Cam kết của chúng tôi',
    'cs.commit_1':'Hoàn tiền trong 3-5 ngày làm việc',
    'cs.commit_2':'Hỗ trợ 24/7 khi có vấn đề',
    'cs.commit_3':'Trung lập, công bằng với cả 2 bên',
    'cs.last_updated':'Cập nhật lần cuối: 04/05/2024 — Phiên bản 1.2',
    'cs.s1_h':'Chính Sách Hoàn Tiền',
    'cs.s1_p':'GuideTravel áp dụng chính sách hoàn tiền dựa trên thời điểm hủy tour. Chúng tôi cam kết xử lý hoàn tiền trong vòng <strong>3–5 ngày làm việc</strong> kể từ khi xác nhận yêu cầu hợp lệ.',
    'cs.th_time':'Thời điểm hủy','cs.th_tourist':'Khách nhận lại','cs.th_guide':'HDV nhận','cs.th_note':'Ghi chú',
    'cs.r1_time':'<strong>Trước 7 ngày</strong> trở lên','cs.r1_tourist':'100% tiền cọc','cs.r1_guide':'0đ','cs.r1_note':'Hoàn đầy đủ, không điều kiện',
    'cs.r2_time':'<strong>3 – 7 ngày</strong> trước tour','cs.r2_tourist':'50% tiền cọc','cs.r2_guide':'50% tiền cọc','cs.r2_note':'HDV đã chuẩn bị, bồi thường một phần',
    'cs.r3_time':'<strong>1 – 3 ngày</strong> trước tour','cs.r3_tourist':'0%','cs.r3_guide':'100% tiền cọc','cs.r3_note':'HDV không kịp nhận khách khác',
    'cs.r4_time':'<strong>Ngày đi</strong> (< 24h)','cs.r4_tourist':'0%','cs.r4_guide':'100% tiền cọc','cs.r4_note':'Không hoàn trong mọi trường hợp',
    'cs.s1_note':'<strong>Lưu ý về tiền cọc:</strong> Khách đặt cọc 30% tổng giá trị tour khi xác nhận lịch trình. 70% còn lại thanh toán trước ngày đi 3 ngày. Chính sách hoàn tiền áp dụng cho toàn bộ số tiền đã thanh toán.',
    'cs.s2_h':'Chính Sách Hủy Tour',
    'cs.s2_tourist_h':'Khách hủy tour',
    'cs.s2_t1_title':'Cách hủy hợp lệ',
    'cs.s2_t1_desc':'Gửi yêu cầu hủy qua email hello@guidetravel.vn hoặc hotline 1900 123 456. Yêu cầu phải ghi rõ mã đơn hàng, lý do hủy và được xác nhận bởi nhân viên GuideTravel.',
    'cs.s2_t2_title':'Thời gian xử lý',
    'cs.s2_t2_desc':'Xác nhận hủy trong 2 giờ làm việc. Tiền hoàn về tài khoản/ví trong 3–5 ngày làm việc tùy ngân hàng.',
    'cs.s2_guide_h':'HDV hủy tour',
    'cs.s2_g1_title':'Khách được hoàn 100% ngay lập tức',
    'cs.s2_g1_desc':'Khi HDV hủy vì bất kỳ lý do gì, khách được hoàn toàn bộ số tiền đã thanh toán trong vòng 24 giờ.',
    'cs.s2_g2_title':'Trừ điểm uy tín HDV',
    'cs.s2_g2_desc':'Mỗi lần hủy bị trừ 1 điểm uy tín. Đủ 3 lần hủy không có lý do chính đáng → tài khoản bị đình chỉ 30 ngày. Đủ 5 lần → khóa vĩnh viễn.',
    'cs.s2_g3_title':'Hỗ trợ ghép HDV thay thế',
    'cs.s2_g3_desc':'GuideTravel chủ động tìm HDV thay thế phù hợp cho khách. Nếu không tìm được, khách được hoàn 100% và nhận voucher giảm 10% cho lần đặt tiếp theo.',
    'cs.s3_h':'Trường Hợp Bất Khả Kháng',
    'cs.s3_p':'GuideTravel công nhận các trường hợp bất khả kháng và áp dụng chính sách hoàn tiền linh hoạt hơn khi có bằng chứng hợp lệ.',
    'cs.force1_h':'Thiên tai, thời tiết cực đoan',
    'cs.force1_p':'Bão, lũ lụt, động đất làm gián đoạn chuyến đi. Hoàn <strong>80–100%</strong> khi có thông báo cảnh báo thiên tai từ cơ quan có thẩm quyền.',
    'cs.force2_h':'Chuyến bay bị hủy / trễ',
    'cs.force2_p':'Hãng bay hủy chuyến ngoài ý muốn. Hoàn <strong>80%</strong> khi cung cấp xác nhận hủy chuyến bay từ hãng.',
    'cs.force3_h':'Sức khỏe khẩn cấp',
    'cs.force3_p':'Bản thân hoặc người thân cần nhập viện khẩn cấp. Hoàn <strong>80–100%</strong> khi có giấy xác nhận từ bệnh viện.',
    'cs.force4_h':'Dịch bệnh / Lệnh phong tỏa',
    'cs.force4_p':'Chính phủ ban hành lệnh hạn chế di chuyển. Hoàn <strong>100%</strong> toàn bộ tiền đã thanh toán.',
    'cs.force5_h':'Vấn đề visa (khách nước ngoài)',
    'cs.force5_p':'Visa bị từ chối hoặc hết hạn ngoài ý muốn. Hoàn <strong>80%</strong> khi có bằng chứng từ cơ quan xuất nhập cảnh.',
    'cs.force6_h':'Tang lễ gia đình',
    'cs.force6_p':'Thành viên gia đình trực tiếp qua đời. Hoàn <strong>100%</strong> khi có giấy xác nhận.',
    'cs.s3_note':'<strong>Lưu ý:</strong> Tất cả yêu cầu hoàn tiền bất khả kháng cần gửi bằng chứng trong vòng <strong>48 giờ</strong> kể từ khi sự kiện xảy ra. GuideTravel có quyền từ chối nếu bằng chứng không hợp lệ hoặc gửi trễ.',
    'cs.s4_h':'Giải Quyết Tranh Chấp',
    'cs.s4_p':'GuideTravel đóng vai trò <strong>trung gian trung lập</strong> trong mọi tranh chấp giữa khách và HDV.',
    'cs.s4_flow_h':'Quy trình xử lý khiếu nại',
    'cs.f1_title':'Khách gửi khiếu nại (trong 24h sau tour)',
    'cs.f1_desc':'Mô tả vấn đề + đính kèm bằng chứng (ảnh, video, tin nhắn). Gửi qua email hoặc hotline.',
    'cs.f2_title':'GuideTravel thu thập thông tin (24–48h)',
    'cs.f2_desc':'Liên hệ cả 2 bên, xem xét lịch trình đã thỏa thuận, bằng chứng và lịch sử chat.',
    'cs.f3_title':'Đưa ra phán quyết (trong 72h)',
    'cs.f3_desc':'Thông báo kết quả cho cả 2 bên. Mức hoàn tiền từ 0–100% tùy mức độ lỗi.',
    'cs.f4_title':'Thực hiện hoàn tiền (3–5 ngày làm việc)',
    'cs.f4_desc':'Chuyển khoản về tài khoản đã đăng ký. Trường hợp khách nước ngoài: chuyển qua PayPal hoặc Wise.',
    'cs.s4_table_h':'Mức hoàn tiền khi có tranh chấp',
    'cs.th_situation':'Tình huống','cs.th_amount':'Mức hoàn',
    'cs.d1_sit':'HDV không xuất hiện đúng giờ (trễ > 1h không báo trước)','cs.d2_sit':'Lịch trình thực tế khác nhiều so với đã thỏa thuận',
    'cs.d3_sit':'HDV có thái độ không chuyên nghiệp (có bằng chứng)','cs.d4_sit':'Chất lượng dịch vụ thấp hơn mô tả (có bằng chứng)',
    'cs.d5_sit':'Khiếu nại không có bằng chứng cụ thể','cs.d6_sit':'Khiếu nại sau 48h kể từ khi tour kết thúc',
    'cs.s5_h':'Bảo Vệ Toàn Vẹn Nền Tảng',
    'cs.s5_p':'Để đảm bảo công bằng và an toàn cho tất cả, GuideTravel áp dụng các quy định bảo vệ hệ thống:',
    'cs.p1_title':'Nghiêm cấm giao dịch ngoài nền tảng',
    'cs.p1_desc':'HDV không được yêu cầu khách thanh toán trực tiếp để tránh hoa hồng. Vi phạm lần 1: cảnh cáo. Lần 2: khóa tài khoản vĩnh viễn và không hoàn phí đăng ký.',
    'cs.p2_title':'Giữ tiền trong escrow 48h sau tour',
    'cs.p2_desc':'Tiền chỉ được giải ngân cho HDV sau 48h kể từ khi tour kết thúc và khách không có khiếu nại. Điều này bảo vệ khách khỏi các trường hợp dịch vụ kém chất lượng.',
    'cs.p3_title':'Hết hạn khiếu nại sau 30 ngày',
    'cs.p3_desc':'GuideTravel không xem xét bất kỳ khiếu nại nào được gửi sau 30 ngày kể từ ngày tour kết thúc.',
    'cs.p4_title':'Bảo mật thông tin thanh toán',
    'cs.p4_desc':'GuideTravel không lưu trữ thông tin thẻ ngân hàng. Mọi giao dịch đều được mã hóa SSL và xử lý qua cổng thanh toán được cấp phép.',
    'cs.s5_note':'<strong>Quyền lợi của bạn:</strong> Nếu HDV vi phạm và bạn có bằng chứng, hãy báo cáo ngay cho GuideTravel. Chúng tôi cam kết xử lý trong 24h và bảo vệ quyền lợi của bạn đến cùng.',
    'cs.s6_h':'Quy Trình Thanh Toán',
    'cs.pay_domestic_h':'Khách trong nước',
    'cs.pay_intl_h':'Khách nước ngoài',
    'cs.pay_fee_domestic':'Phí xử lý: 0 – 1.1%',
    'cs.pay_fee_intl':'Phí xử lý: 2.9% + 30¢',
    'cs.pay_struct_h':'Cấu trúc thanh toán',
    'cs.th_when':'Thời điểm','cs.th_amount2':'Số tiền','cs.th_purpose':'Mục đích',
    'cs.pay1_when':'Khi xác nhận lịch trình','cs.pay1_amount':'<strong>30%</strong> tổng giá trị','cs.pay1_purpose':'Đặt cọc — platform giữ',
    'cs.pay2_when':'Trước tour 3 ngày','cs.pay2_amount':'<strong>70%</strong> còn lại','cs.pay2_purpose':'Thanh toán đủ — platform giữ',
    'cs.pay3_when':'48h sau khi tour xong','cs.pay3_amount':'<strong>85–100%</strong> tùy hoa hồng','cs.pay3_purpose':'Giải ngân cho HDV',
    'cs.s7_h':'Liên Hệ Hỗ Trợ',
    'cs.s7_p':'Nếu bạn cần hỗ trợ về thanh toán hoặc khiếu nại, đội ngũ GuideTravel luôn sẵn sàng:',
    'cs.phone_hours':'8:00 – 22:00 hàng ngày',
    'cs.email_resp':'Phản hồi trong 2 giờ',
    'cs.messenger_addr':'m.me/GuideTravel',
    'cs.s7_note':'Khi liên hệ, vui lòng cung cấp <strong>mã đơn hàng</strong> và <strong>mô tả vấn đề</strong> để được hỗ trợ nhanh nhất. Đối với khiếu nại, hãy đính kèm bằng chứng (ảnh, video, tin nhắn) để chúng tôi xử lý chính xác.',
  },

  en: {
    // NAV
    'nav.home':'Home','nav.find_guide':'Find Guides','nav.post_request':'Post Request',
    'nav.become_guide':'Become a Guide','nav.login':'Login','nav.logout':'Logout',
    'nav.dashboard':'Dashboard','nav.tourist_dash':'My Dashboard',
    // GUIDE CARD
    'card.verified':'Verified','card.reviews':'reviews','card.from':'From',
    'card.per_day':'/ day','card.view_profile':'View Profile',
    'card.experience':'years experience','card.response_time':'Response',
    // INDEX
    'home.trust_badge':'Vietnam\'s #1 Trusted Platform',
    'home.hero_title':'<span>Personalized</span> travel itineraries just for you',
    'home.hero_sub':'Want to explore Vietnam but don\'t know where to start? Connect with a local guide — they\'ll design a 100% custom itinerary based on your interests.',
    'home.search_ph':'Where do you want to go? Nha Trang, Da Lat, Sapa...',
    'home.search_btn':'Find a Guide',
    'home.how_tag':'How it works','home.how_title':'Simple 3 steps',
    'home.how_sub':'No need to spend hours planning — local guides handle everything for you',
    'home.step1_t':'Find a Guide','home.step1_d':'Browse local guides by destination, budget and verified reviews.',
    'home.step2_t':'Send a Request','home.step2_d':'Share your interests, budget and dates — your guide creates a custom itinerary within 24h.',
    'home.step3_t':'Explore','home.step3_d':'Confirm your itinerary, pay securely through the platform, and enjoy your trip.',
    'home.feat_tag':'Top Guides','home.feat_title':'Most Loved Guides',
    'home.feat_sub':'Top-rated local guides trusted by hundreds of travelers',
    'home.see_all':'See all',
    'home.dest_tag':'Destinations','home.dest_title':'Explore Vietnam',
    'home.dest_sub':'Local guides with deep knowledge at every destination — from southern beaches to northern mountains',
    'home.stat_happy':'Happy travelers','home.stat_guides':'Verified guides',
    'home.stat_dest':'Destinations','home.stat_rate':'Satisfaction',
    'home.why_tag':'Why choose us','home.why_title':'A Different Experience',
    'home.w1_t':'100% Personalized','home.w1_d':'Itineraries designed around your interests, budget and schedule.',
    'home.w2_t':'Real Local Guides','home.w2_d':'Locals who know the best food spots and hidden gems that regular tours miss.',
    'home.w3_t':'Safe Payments','home.w3_d':'Funds held by the platform and released only after your trip is completed.',
    'home.w4_t':'Verified Guides','home.w4_d':'All guides are ID-verified with authentic reviews from real travelers.',
    'home.cta_title':'Your dream trip starts here',
    'home.cta_sub':'Send a free request — guides respond within 24 hours',
    'home.cta_btn':'Send Free Request','home.cta_browse':'Browse All Guides',
    // GUIDES PAGE
    'guides.title':'Find Tour Guides',
    'guides.sub':'Over 50 verified local guides — find the perfect match for your trip',
    'guides.filter':'Filters','guides.dest_label':'Destination','guides.all_dest':'All destinations',
    'guides.price_label':'Price / day (max)','guides.rating_label':'Minimum rating',
    'guides.all_ratings':'All','guides.clear':'Clear filters',
    'guides.tip_title':'💡 Pro tip',
    'guides.tip_text':'Not sure which guide to pick? <a href="request.html" style="color:var(--blue);font-weight:600">Post a request</a> — we\'ll match you with the best guide for your trip!',
    'guides.popular':'Most popular','guides.top_rated':'Highest rated',
    'guides.price_asc':'Lowest price','guides.price_desc':'Highest price',
    'guides.count_suffix':'guides',
    'guides.no_result':'No guides found','guides.no_result_sub':'Try changing the filters',
    // PROFILE PAGE
    'profile.about':'About','profile.itineraries':'Sample Itineraries',
    'profile.itin_note':'These are sample itineraries. The guide will customize them based on your preferences.',
    'profile.reviews':'Guest Reviews','profile.trips':'Tours led',
    'profile.reviews_stat':'Reviews','profile.per_day':'/ day',
    'profile.price_from':'Service price from',
    'profile.price_note':'Final price depends on itinerary & your requirements',
    'profile.start_date':'Start date','profile.num_days':'Number of days','profile.num_people':'Number of people',
    'profile.estimated':'Estimated','profile.send_request':'Send Request',
    'profile.free':'Free to send a request','profile.resp_24h':'Guide responds within 24h',
    'profile.pay_after':'Pay after finalizing the itinerary','profile.share':'Share this profile',
    // REQUEST PAGE
    'req.title':'Post Your Trip Request',
    'req.sub':'Describe your ideal trip — the right guide will contact you within 24 hours',
    'req.name':'Full name','req.phone':'Phone number','req.email':'Email',
    'req.dest':'Desired destination','req.date':'Planned start date',
    'req.days':'Number of days','req.people':'Number of people','req.budget':'Budget',
    'req.interests':'Interests & Activities','req.notes':'Additional notes',
    'req.notes_ph':'More details about your trip...','req.submit':'Submit Request',
    'req.free_note':'Free · No commitment · Guide contacts you within 24h',
    // PAYMENT PAGE
    'pay.contact':'Contact Information','pay.name':'Full name','pay.phone':'Phone number',
    'pay.email':'Email','pay.notes':'Additional notes','pay.notes_ph':'Special requests, preferences...',
    'pay.method':'Payment Method','pay.domestic':'🇻🇳 Domestic (Vietnam)','pay.intl':'🌍 International',
    'pay.escrow':'<i class="fa-solid fa-shield-halved" style="margin-right:6px"></i><strong>Safe escrow payment:</strong> Your money is held by GuideTravel and only transferred to the guide after your tour is completed.',
    'pay.confirm_btn':'<i class="fa-solid fa-lock"></i> Confirm & Pay Securely',
    'pay.ssl_note':'<i class="fa-solid fa-shield-halved"></i> SSL encrypted. Free cancellation up to 7 days before.',
    'pay.summary':'Booking Summary','pay.start_date':'Start date','pay.days':'Days',
    'pay.people':'People','pay.unit_price':'Price per day','pay.service_fee':'Service fee',
    'pay.free':'Free','pay.total':'Total',
    'pay.trust1':'100% refund if cancelled 7+ days before','pay.trust2':'Guide confirms within 24h',
    'pay.trust3':'Payment protected','pay.trust4':'24/7 support throughout your trip',
    'pay.view_policy':'View refund policy',
    'pay.success_title':'Booking Successful!',
    'pay.success_sub':'Your request has been sent to the guide. They will contact you within 24 hours to confirm the itinerary.',
    'pay.save_code':'Save this code to track your request',
    'pay.back_home':'Back to Home','pay.find_more':'Find More Guides',
    'pay.step1':'Choose Guide','pay.step2':'Fill Details','pay.step3':'Payment','pay.step4':'Confirm',
    // LOGIN
    'login.platform_sub':'Connecting travelers with local tour guides',
    'login.tab_login':'Login','login.tab_register':'Register',
    'login.tourist':'Traveler','login.guide':'Tour Guide',
    'login.email_ph':'email@example.com','login.pass_ph':'••••••••',
    'login.login_btn':'<i class="fa-solid fa-right-to-bracket"></i> Login',
    'login.no_account':'Don\'t have an account?','login.register_now':'Register now',
    'login.name_ph':'John Smith','login.phone_ph':'+84 912 345 678',
    'login.pass_ph2':'Minimum 6 characters',
    'login.create_btn':'<i class="fa-solid fa-user-plus"></i> Create Account',
    'login.have_account':'Already have an account?','login.login_link':'Login',
    // FOOTER
    'footer.brand_sub':'Connecting travelers with local guides to create unforgettable personalized journeys.',
    'footer.explore':'Explore','footer.services':'Services','footer.contact':'Contact',
    'footer.find_guides':'Find Guides','footer.post_request':'Post a request',
    'footer.all_dest':'All destinations','footer.become_guide':'Become a Guide',
    'footer.refund':'Refund Policy','footer.faq':'FAQ',
    'footer.copyright':'© 2024 GuideTravel. All rights reserved.',
    'footer.brand_tagline':'Personalized travel connection platform',
    // DESTINATIONS
    'dest.beach':'Beach & Islands','dest.culture':'Culture','dest.trekking':'Trekking',
    'dest.nature':'Nature','dest.island':'Pearl Island',
    // GUIDES PAGE EXTRA
    'guides.breadcrumb':'Find Guides',
    'guides.search_lbl':'Search by name','guides.search_ph':'Guide name...',
    'guides.lang_lbl':'Guide language','guides.lang_all':'All languages',
    'guides.filter_h':'Filters','guides.dest_filter':'Destination',
    'guides.dest_all':'All destinations','guides.price_max':'Price / day (max)',
    'guides.rating_min':'Minimum rating','guides.reset':'Clear filters',
    'guides.tip_h':'💡 Pro tip',
    'guides.dest_title':'Destinations','guides.services_title':'Services',
    // REQUEST PAGE EXTRA
    'req.page_title':'Describe Your Trip',
    'req.page_sub':'Takes 2 minutes — guides will send an itinerary within 24 hours',
    'req.form_title':'Trip Details',
    'req.form_sub':'The more details you share, the better your guide can tailor the itinerary',
    'req.your_info':'Your information','req.trip_info':'Trip details',
    'req.likes':'What do you enjoy?','req.pick_multi':'(select multiple)',
    'req.extra_notes':'Additional requests / Notes',
    'req.notes_hint':'This helps your guide design a more tailored itinerary',
    'req.submit_btn':'Send Free Request',
    'req.privacy':'Your information is kept private',
    'req.next_title':'What happens next?',
    'req.s1t':'Guide receives your request','req.s1d':'Within a few hours, a suitable guide will review your request',
    'req.s2t':'Get itinerary within 24h','req.s2d':'Guide sends a detailed itinerary + quote via email/phone',
    'req.s3t':'Free revisions','req.s3d':'Adjust the itinerary as many times as you like until you\'re happy',
    'req.s4t':'Confirm & Deposit','req.s4d':'Pay a 30% deposit securely through the platform to lock in your dates',
    'req.suggest_h':'Guides that may suit you','req.suggest_all':'View all guides →',
    'req.pledge_h':'GuideTravel Guarantee',
    'req.pledge1':'Completely free to submit a request',
    'req.pledge2':'No pressure to book if you\'re not ready',
    'req.pledge3':'100% refund if cancelled 7+ days before',
    'req.success_h':'Request Sent! 🎉',
    'req.success_p':'Thank you for your request. Your guide will contact you by phone and email within <strong>24 hours</strong> with a personalized itinerary.',
    'req.code_lbl':'Your request code',
    'req.waiting_h':'While you wait...',
    'req.wait1':'Check your email for notifications',
    'req.wait2':'Watch your phone — your guide may call directly',
    'req.wait3':'Browse more guide profiles',
    'req.see_more':'Browse More Guides','req.back_home':'Home',
    // PROFILE PAGE EXTRA
    'profile.resp_lbl':'Response',
    'profile.about_h':'About','profile.itin_h':'Sample Itineraries',
    'profile.reviews_h':'Guest Reviews',
    'profile.price_from_lbl':'Service price from','profile.per_day_lbl':'/ day',
    'profile.price_note_lbl':'Final price depends on itinerary & your requirements',
    'profile.start_lbl':'Start date','profile.days_lbl':'Number of days','profile.people_lbl':'Number of people',
    'profile.est_lbl':'Estimated','profile.req_btn':'Send Request',
    'profile.g1':'Free to send a request','profile.g2':'Guide responds within 24h',
    'profile.g3':'Pay after finalizing itinerary',
    'profile.share_h':'Share this profile',
    // LOGIN EXTRA
    'login.pass_lbl':'Password','login.name_lbl':'Full name',
    'login.phone_lbl':'Phone number',
    'login.login_btn_text':'Login','login.create_text':'Create Account',
    // UNITS
    'unit.days':'days','unit.hours':'hours','unit.people':'people',
    // SPECIALTIES
    'spec.Biển đảo':'Beach & Islands','spec.Lặn biển':'Diving','spec.Ẩm thực':'Food & Cuisine',
    'spec.Văn hóa':'Culture','spec.Lịch sử':'History','spec.Chụp ảnh':'Photography',
    'spec.Trekking':'Trekking','spec.Văn hóa dân tộc':'Ethnic Culture',
    'spec.Nhiếp ảnh':'Photography','spec.Cắm trại':'Camping',
    'spec.Thiên nhiên':'Nature','spec.Cà phê':'Café & Coffee',
    // INTERESTS
    'int.beach':'Beach & Swimming','int.trekking':'Trekking','int.food':'Food & Cuisine',
    'int.culture':'Culture','int.photo':'Photography','int.shopping':'Shopping',
    'int.relax':'Relaxation','int.village':'Village Life','int.watersport':'Water Sports',
    // PAYMENT EXTRA
    'pay.page_title':'Confirm & Pay',
    'pay.bank_transfer':'Bank Transfer',
    'pay.wise_fee':'Lowest fees',
    // NAV
    'nav.about':'About','nav.blog':'Blog',
    // BLOG
    'blog.title':'Vietnam Travel Blog',
    'blog.sub':'Real tips from local guides — destinations, tricks, budgets',
    'blog.search_ph':'Search articles...',
    'blog.cat_all':'All','blog.cat_dest':'Destinations','blog.cat_tip':'Tips','blog.cat_guide':'Guides',
    'blog.popular':'Popular posts','blog.tags':'Topics',
    'blog.cta_h':'Ready to explore?','blog.cta_p':'Send a free request — a local guide will create a custom itinerary for you.',
    'blog.cta_btn':'Post a request now',
    // POST
    'post.share':'Share:','post.copy_link':'Copy link',
    'post.related':'Related posts','post.toc':'Contents',
    'post.guides_region':'Guides in this area','post.see_all_guides':'See all guides',
    // ABOUT PAGE
    'about.tag':'Our Story',
    'about.hero_title':'Vietnam travel should be<br><span style="color:var(--blue)">experienced like a local</span>',
    'about.hero_sub':'GuideTravel was born from a simple question: Why do foreign travelers pay for overcrowded tours when knowledgeable locals are right there beside them?',
    'about.mission_tag':'Mission','about.mission_title':'Connecting people, not just destinations',
    'about.mission_p1':'We believe real travel begins when you meet a local — someone who knows which alley has the best pho, which beach has no tourists yet, which festival only happens once a year.',
    'about.mission_p2':'GuideTravel directly connects travelers with verified local guides — no middlemen, no cookie-cutter itineraries, 100% personalized.',
    'about.values_tag':'Core Values','about.values_title':'What we believe in',
    'about.v1_t':'Trust & Transparency','about.v1_d':'Every guide is ID-verified with certified credentials. All reviews are from real travelers, never edited.',
    'about.v2_t':'Total Personalization','about.v2_d':'No copy-paste itineraries. Every trip is designed around your interests, budget and schedule.',
    'about.v3_t':'Supporting Local Communities','about.v3_d':'80% of revenue goes to guides and local communities. Responsible tourism for environment and culture.',
    'about.v4_t':'Safe & Secure','about.v4_d':'Escrow payments protect both sides. Funds are only released after the tour is completed and confirmed.',
    'about.how_tag':'How we work','about.how_title':'A transparent<br>marketplace model',
    'about.how_p':'GuideTravel works like a marketplace: we connect and verify, while guides set their own prices.',
    'about.how_s1t':'Guides apply & get verified','about.how_s1d':'ID check, guide license verification, in-person interview',
    'about.how_s2t':'Traveler sends a free request','about.how_s2d':'Describe your trip — the best-fit guide responds within 24h',
    'about.how_s3t':'Safe escrow payment','about.how_s3d':'Funds held by platform, released after tour completion',
    'about.how_s4t':'Real, transparent reviews','about.how_s4d':'Only travelers who completed a tour can review their guide',
    'about.revenue_title':'Revenue split','about.rev_guide':'Guide receives',
    'about.rev_platform':'Platform (ops & support)','about.rev_note':'Guides can choose a 15–30% commission tier to rank higher in search. No hidden fees, no signup cost.',
    'about.story_tag':'Our History','about.story_title':'From idea to platform',
    'about.tl1_t':'The idea sparks','about.tl1_d':'Founder experienced a mass tour in Hoi An and discovered the difference a local guide makes.',
    'about.tl2_t':'First test','about.tl2_d':'Beta launched with 5 guides in Nha Trang and Hoi An. First 50 bookings in 3 months.',
    'about.tl3_t':'Nationwide expansion','about.tl3_d':'Expanded to 8 provinces, onboarded 50+ guides, reached 500 total bookings.',
    'about.tl4_t':'Going international','about.tl4_d':'Launched English UI, integrated Stripe for international payments, targeting 1,000 bookings/month.',
    'about.team_tag':'Team','about.team_title':'The people behind GuideTravel',
    'about.role_ceo':'Co-founder & CEO','about.bio_ceo':'10 years in travel industry, former product manager at Traveloka Vietnam.',
    'about.role_cto':'Co-founder & CTO','about.bio_cto':'8-year full-stack engineer, built booking systems for 50K+ users.',
    'about.role_ops':'Head of Guide Operations','about.bio_ops':'Former international guide for 6 years, responsible for guide vetting and training.',
    'about.cta_title':'Ready for a different experience?','about.cta_sub':'Send a free request — local guides respond within 24 hours',
    // 404 PAGE
    'err.title':'This page hasn\'t been explored yet',
    'err.sub':'Looks like you\'ve wandered off the map. Let us guide you back on track.',
    'err.go_home':'Go Home','err.browse_guides':'Find Guides',
    'err.popular':'Or check these popular pages:',
    // TOAST / VALIDATION
    'err.select_date':'Please select a start date!',
    'err.fill_form':'Please fill in all required fields!',
    // COMMISSION TIERS
    'tier.top':'🏆 Top #1','tier.featured':'⭐ Featured','tier.priority':'👍 Priority',
    // REQUEST
    'req.all_guides':'All matching guides',
    'review.you':'You',
    // CHINH SACH PAGE
    'cs.breadcrumb':'Policy',
    'cs.page_h1':'Refund & Protection Policy',
    'cs.page_sub':'Transparent — fair — protecting the rights of all parties',
    'cs.nav_contents':'Contents',
    'cs.nav_refund':'Refund Policy',
    'cs.nav_cancel':'Tour Cancellation',
    'cs.nav_force':'Force Majeure',
    'cs.nav_dispute':'Dispute Resolution',
    'cs.nav_protect':'Platform Protection',
    'cs.nav_payment':'Payment Process',
    'cs.nav_support':'Contact Support',
    'cs.commit_title':'Our Commitment',
    'cs.commit_1':'Refund within 3–5 working days',
    'cs.commit_2':'24/7 support when issues arise',
    'cs.commit_3':'Neutral and fair to both parties',
    'cs.last_updated':'Last updated: 04/05/2024 — Version 1.2',
    'cs.s1_h':'Refund Policy',
    'cs.s1_p':'GuideTravel applies a refund policy based on when the tour is cancelled. We commit to processing refunds within <strong>3–5 working days</strong> from the time a valid request is confirmed.',
    'cs.th_time':'Cancellation time','cs.th_tourist':'Tourist receives','cs.th_guide':'Guide receives','cs.th_note':'Note',
    'cs.r1_time':'<strong>7+ days</strong> before tour','cs.r1_tourist':'100% deposit','cs.r1_guide':'$0','cs.r1_note':'Full refund, no conditions',
    'cs.r2_time':'<strong>3–7 days</strong> before tour','cs.r2_tourist':'50% deposit','cs.r2_guide':'50% deposit','cs.r2_note':'Guide has prepared, partial compensation',
    'cs.r3_time':'<strong>1–3 days</strong> before tour','cs.r3_tourist':'0%','cs.r3_guide':'100% deposit','cs.r3_note':'Guide cannot find another booking in time',
    'cs.r4_time':'<strong>Day of tour</strong> (< 24h)','cs.r4_tourist':'0%','cs.r4_guide':'100% deposit','cs.r4_note':'No refund under any circumstances',
    'cs.s1_note':'<strong>Note on deposit:</strong> Tourists pay a 30% deposit of the total tour value upon confirming the itinerary. The remaining 70% is paid 3 days before the tour. The refund policy applies to all amounts paid.',
    'cs.s2_h':'Tour Cancellation Policy',
    'cs.s2_tourist_h':'Tourist cancels',
    'cs.s2_t1_title':'Valid cancellation method',
    'cs.s2_t1_desc':'Submit a cancellation request via email hello@guidetravel.vn or hotline 1900 123 456. The request must include the order ID, reason for cancellation, and be confirmed by GuideTravel staff.',
    'cs.s2_t2_title':'Processing time',
    'cs.s2_t2_desc':'Cancellation confirmed within 2 working hours. Refund to account/wallet within 3–5 working days depending on bank.',
    'cs.s2_guide_h':'Guide cancels',
    'cs.s2_g1_title':'Tourist receives 100% refund immediately',
    'cs.s2_g1_desc':'When a guide cancels for any reason, the tourist receives a full refund of all amounts paid within 24 hours.',
    'cs.s2_g2_title':'Guide credibility points deducted',
    'cs.s2_g2_desc':'Each cancellation deducts 1 credibility point. 3 unjustified cancellations → account suspended for 30 days. 5 cancellations → permanent ban.',
    'cs.s2_g3_title':'Replacement guide assistance',
    'cs.s2_g3_desc':'GuideTravel proactively finds a suitable replacement guide. If unavailable, the tourist receives a 100% refund plus a 10% discount voucher for their next booking.',
    'cs.s3_h':'Force Majeure Cases',
    'cs.s3_p':'GuideTravel recognizes force majeure cases and applies a more flexible refund policy when valid evidence is provided.',
    'cs.force1_h':'Natural disasters, extreme weather',
    'cs.force1_p':'Storms, floods, or earthquakes disrupting the trip. Refund of <strong>80–100%</strong> with official disaster warning notice from authorities.',
    'cs.force2_h':'Flight cancelled / delayed',
    'cs.force2_p':'Airline cancels flight unexpectedly. Refund of <strong>80%</strong> with confirmed flight cancellation from the airline.',
    'cs.force3_h':'Medical emergency',
    'cs.force3_p':'Tourist or close family member requires emergency hospitalization. Refund of <strong>80–100%</strong> with hospital confirmation letter.',
    'cs.force4_h':'Epidemic / Government lockdown',
    'cs.force4_p':'Government issues movement restriction orders. <strong>100%</strong> refund of all amounts paid.',
    'cs.force5_h':'Visa issues (foreign tourists)',
    'cs.force5_p':'Visa denied or expired unexpectedly. Refund of <strong>80%</strong> with evidence from immigration authority.',
    'cs.force6_h':'Family bereavement',
    'cs.force6_p':'Immediate family member passes away. <strong>100%</strong> refund with confirmation document.',
    'cs.s3_note':'<strong>Note:</strong> All force majeure refund requests must submit evidence within <strong>48 hours</strong> of the event. GuideTravel reserves the right to reject requests if evidence is invalid or submitted late.',
    'cs.s4_h':'Dispute Resolution',
    'cs.s4_p':'GuideTravel acts as a <strong>neutral mediator</strong> in all disputes between tourists and guides.',
    'cs.s4_flow_h':'Complaint handling process',
    'cs.f1_title':'Tourist files complaint (within 24h after tour)',
    'cs.f1_desc':'Describe the issue + attach evidence (photos, videos, messages). Submit via email or hotline.',
    'cs.f2_title':'GuideTravel collects information (24–48h)',
    'cs.f2_desc':'Contact both parties, review the agreed itinerary, evidence, and chat history.',
    'cs.f3_title':'Issue ruling (within 72h)',
    'cs.f3_desc':'Notify both parties of the outcome. Refund rate of 0–100% depending on degree of fault.',
    'cs.f4_title':'Process refund (3–5 working days)',
    'cs.f4_desc':'Transfer to registered account. For foreign tourists: via PayPal or Wise.',
    'cs.s4_table_h':'Refund amounts in disputes',
    'cs.th_situation':'Situation','cs.th_amount':'Refund',
    'cs.d1_sit':'Guide did not arrive on time (late > 1h without notice)','cs.d2_sit':'Actual itinerary significantly different from what was agreed',
    'cs.d3_sit':'Guide behaved unprofessionally (with evidence)','cs.d4_sit':'Service quality below description (with evidence)',
    'cs.d5_sit':'Complaint with no specific evidence','cs.d6_sit':'Complaint filed 48h+ after tour ended',
    'cs.s5_h':'Platform Integrity Protection',
    'cs.s5_p':'To ensure fairness and safety for all, GuideTravel applies the following system protection rules:',
    'cs.p1_title':'Off-platform transactions strictly prohibited',
    'cs.p1_desc':'Guides may not ask tourists to pay directly to avoid commission. 1st violation: warning. 2nd: permanent account ban with no refund of registration fees.',
    'cs.p2_title':'Funds held in escrow for 48h after tour',
    'cs.p2_desc':'Funds are only released to the guide 48 hours after the tour ends and no complaint has been filed. This protects tourists from poor service.',
    'cs.p3_title':'Complaint expiry after 30 days',
    'cs.p3_desc':'GuideTravel will not consider any complaints submitted more than 30 days after the tour end date.',
    'cs.p4_title':'Payment information security',
    'cs.p4_desc':'GuideTravel does not store bank card details. All transactions are SSL-encrypted and processed through licensed payment gateways.',
    'cs.s5_note':'<strong>Your rights:</strong> If a guide violates the rules and you have evidence, report it to GuideTravel immediately. We commit to handling it within 24h and protecting your rights fully.',
    'cs.s6_h':'Payment Process',
    'cs.pay_domestic_h':'Domestic tourists',
    'cs.pay_intl_h':'International tourists',
    'cs.pay_fee_domestic':'Processing fee: 0 – 1.1%',
    'cs.pay_fee_intl':'Processing fee: 2.9% + 30¢',
    'cs.pay_struct_h':'Payment structure',
    'cs.th_when':'When','cs.th_amount2':'Amount','cs.th_purpose':'Purpose',
    'cs.pay1_when':'Upon confirming itinerary','cs.pay1_amount':'<strong>30%</strong> of total','cs.pay1_purpose':'Deposit — held by platform',
    'cs.pay2_when':'3 days before tour','cs.pay2_amount':'Remaining <strong>70%</strong>','cs.pay2_purpose':'Full payment — held by platform',
    'cs.pay3_when':'48h after tour ends','cs.pay3_amount':'<strong>85–100%</strong> based on commission','cs.pay3_purpose':'Released to guide',
    'cs.s7_h':'Contact Support',
    'cs.s7_p':'If you need help with payments or complaints, the GuideTravel team is always ready:',
    'cs.phone_hours':'8:00 AM – 10:00 PM daily',
    'cs.email_resp':'Response within 2 hours',
    'cs.messenger_addr':'m.me/GuideTravel',
    'cs.s7_note':'When contacting us, please provide your <strong>order ID</strong> and <strong>description of the issue</strong> for the fastest support. For complaints, attach evidence (photos, videos, messages) so we can handle it accurately.',
  }
};

// ===== HELPERS =====
function t(key) {
  const lang = localStorage.getItem('gt_lang') || 'vi';
  return TRANS[lang]?.[key] ?? TRANS.vi[key] ?? key;
}

function fmtPrice(n) {
  const lang = localStorage.getItem('gt_lang') || 'vi';
  if (lang === 'en') return '~$' + Math.round(n / 25000);
  return new Intl.NumberFormat('vi-VN').format(n) + 'đ';
}

function setLang(lang) {
  localStorage.setItem('gt_lang', lang);
  document.documentElement.lang = lang;
  applyLang();
  window.dispatchEvent(new CustomEvent('langchange', { detail: { lang } }));
  document.querySelectorAll('.lang-btn').forEach(b => b.classList.toggle('active-lang', b.dataset.lang === lang));
}

function applyLang() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    const attr = el.getAttribute('data-i18n-attr');
    const val = t(key);
    if (attr) el.setAttribute(attr, val);
    else el.innerHTML = val;
  });
}

// Auto-apply on load
document.addEventListener('DOMContentLoaded', () => {
  applyLang();
  // Mark active lang button
  const cur = localStorage.getItem('gt_lang') || 'vi';
  document.querySelectorAll('.lang-btn').forEach(b => b.classList.toggle('active-lang', b.dataset.lang === cur));
});
